#!/bin/bash
video=$(xsel --clipboard)
if [ $? = 0  ];
then
urxvt -e youtube-dl -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --write-sub --write-auto-sub --sub-format ttml --convert-subtitles srt --embed-sub -o "/media/ntfs/Users/Reece/Desktop/Youtube/%(uploader)s - %(playlist)s - %(playlist_index)s - %(title)s.%(ext)s" $video
else exit 0
  fi
  exit 1
